export const LOCAL_MOVIES = [
  {
    id: 'tt10872600',
    title: 'Spider-Man: No Way Home',
    year: '2021',
    type: 'Action',
    rating: '8.2',
    poster: 'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg',
    overview: 'With Spider-Man\'s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.',
  },
  {
    id: 'tt2953050',
    title: 'Encanto',
    year: '2021',
    type: 'Animation',
    rating: '7.2',
    poster: 'https://m.media-amazon.com/images/M/MV5BNjE5NzA4ZDctOTJkZi00NzM0LTkwOTYtMDI4MmNkMzIxODhkXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg',
    overview: 'A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers.',
  },
  {
    id: 'tt7991608',
    title: 'Red Notice',
    year: '2021',
    type: 'Action',
    rating: '6.3',
    poster: 'https://m.media-amazon.com/images/M/MV5BZmRjODgyMzEtMzIxYS00OWY2LTk4YjUtMGMzZjMzMTZiN2Q0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    overview: 'An Interpol-issued Red Notice is a global alert to hunt and capture the world\'s most wanted.',
  },
  {
    id: 'tt12689248',
    title: 'The Commando',
    year: '2022',
    type: 'Action',
    rating: '4.1',
    poster: 'https://m.media-amazon.com/images/M/MV5BYTQ5ZjM3YmQtNTQ4ZC00NzBmLTk5YTUtN2I1NWRhYzcyNzgzXkEyXkFqcGdeQXVyNDA1NDA2NTk@._V1_SX300.jpg',
    overview: 'A DEA agent returns home after a failed mission only to face a deadly threat closer to home.',
  },
  {
    id: 'tt14060094',
    title: 'Blacklight',
    year: '2022',
    type: 'Thriller',
    rating: '5.3',
    poster: 'https://m.media-amazon.com/images/M/MV5BY2ViYmNhNzEtZDJhNS00YzM4LTkzZWItZDJiNzc5ZDExOWZmXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg',
    overview: 'A shadowy government fixer uncovers a deadly conspiracy within his own agency.',
  },
  {
    id: 'tt8097030',
    title: 'Turning Red',
    year: '2022',
    type: 'Animation',
    rating: '7.0',
    poster: 'https://m.media-amazon.com/images/M/MV5BNjY0MGEzZmQtZWMxNi00MWVhLWI4NWEtYjQ0MDkyYTJhMDU0XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_SX300.jpg',
    overview: 'A 13-year-old girl discovers that when she gets too excited, she transforms into a giant red panda.',
  },
  {
    id: 'tt9032400',
    title: 'Eternals',
    year: '2021',
    type: 'Sci-Fi',
    rating: '6.3',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTExZmVjY2ItYTAzYi00MDdlLWFlOWItNTJhMDRjMzQ5ZGY0XkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_SX300.jpg',
    overview: 'The Eternals, a race of immortal beings with superhuman powers, must reunite to protect Earth.',
  },
  {
    id: 'tt7740496',
    title: 'Nightmare Alley',
    year: '2021',
    type: 'Thriller',
    rating: '7.1',
    poster: 'https://m.media-amazon.com/images/M/MV5BOTI4NDhhNGEtZjQxZC00ZTRmLThmZTctOGJmY2ZlOTc0ZGY0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    overview: 'An ambitious carny with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist.',
  },
  {
    id: 'tt13634480',
    title: 'The Ice Age Adventures',
    year: '2022',
    type: 'Animation',
    rating: '5.9',
    poster: 'https://m.media-amazon.com/images/M/MV5BNDJmMzQyMzAtMzMxMy00NTI3LTgzOGMtZDU3Yzc4MjRjNzkwXkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_SX300.jpg',
    overview: 'Buck leads an adventure to the Lost World in this sequel to the beloved Ice Age franchise.',
  },
  {
    id: 'tt9848626',
    title: 'Hotel Transylvania 4',
    year: '2022',
    type: 'Animation',
    rating: '5.7',
    poster: 'https://m.media-amazon.com/images/M/MV5BZWM4MzUyYTAtMGFiYy00MmRkLWIyNDktMWFlMDlmZjJmNWZmXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_SX300.jpg',
    overview: 'Dracula and his friends are turned human, and must find a way to undo the monster-ray\'s magic.',
  },
  {
    id: 'tt9032401',
    title: 'Kimi',
    year: '2022',
    type: 'Thriller',
    rating: '7.0',
    poster: 'https://m.media-amazon.com/images/M/MV5BYjFmOWUwYjgtM2UyYS00M2FmLTgwNmUtMWIwNTc2ZTgzNmRhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg',
    overview: 'An agoraphobic tech worker discovers evidence of a crime through a smart home device.',
  },
  {
    id: 'tt11755740',
    title: 'Texas Chainsaw Massacre',
    year: '2022',
    type: 'Horror',
    rating: '4.5',
    poster: 'https://m.media-amazon.com/images/M/MV5BMDU4Yzk1NmUtNDU4OC00YzVmLTgwOTUtYTY2NjNmMjY5YjVmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    overview: 'After nearly 50 years of hiding, Leatherface returns to terrorize a group of idealistic young friends.',
  },
];

export const GENRE_OPTIONS = [
  'Action', 'Drama', 'Comedy', 'Horror',
  'Fantasy', 'Adventure', 'Thriller', 'Sci-Fi',
  'Animation', 'Romance', 'Mystery', 'Documentary',
];
