import { Link } from 'react-router-dom';
import styles from './LegalPage.module.css';

export default function Terms() {
  return (
    <div className={`container ${styles.page}`}>
      <h1 className={styles.heading}>Terms of Service</h1>
      <p className={styles.updated}>Last updated: July 2026</p>

      <section className={styles.section}>
        <h2>1. About Netfif Cinema</h2>
        <p>
          Netfif Cinema is a personal movie discovery project built for learning and
          portfolio purposes. It lets you browse films, save watchlists, write reviews,
          and get AI-assisted recommendations. It is not a commercial product and is
          provided "as is" without warranty of any kind.
        </p>
      </section>

      <section className={styles.section}>
        <h2>2. Your Account</h2>
        <p>
          You sign in using your Google account via Supabase Authentication. You're
          responsible for keeping your account secure. We reserve the right to remove
          accounts or content that violate these terms (e.g. abusive reviews, spam,
          or attempts to exploit the service).
        </p>
      </section>

      <section className={styles.section}>
        <h2>3. Your Content</h2>
        <p>
          Reviews, ratings, lists, and other content you create remain yours. By posting
          a review, you allow it to be displayed publicly on the platform (including on
          shared links and social previews) and to count toward public features like the
          Leaderboard.
        </p>
      </section>

      <section className={styles.section}>
        <h2>4. Third-Party Services</h2>
        <p>Netfif Cinema relies on the following third-party services to function:</p>
        <ul className={styles.list}>
          <li><strong>TMDB</strong> — movie data, posters, and metadata.</li>
          <li><strong>Supabase</strong> — authentication and database storage.</li>
          <li><strong>Google Gemini</strong> — AI features (chat, review assistant, mood-based discovery).</li>
          <li><strong>Sentry</strong> — error monitoring to help us fix bugs.</li>
          <li><strong>Vercel</strong> — hosting and serverless functions.</li>
        </ul>
        <p>
          This product uses the TMDB API but is not endorsed or certified by TMDB.
        </p>
      </section>

      <section className={styles.section}>
        <h2>5. AI Features</h2>
        <p>
          AI-powered features (chat, review suggestions, mood-based recommendations) are
          generated by Google Gemini and may occasionally be inaccurate. Don't rely on
          AI-generated content as factual or professional advice.
        </p>
      </section>

      <section className={styles.section}>
        <h2>6. Changes</h2>
        <p>
          These terms may be updated as the project evolves. Continued use of Netfif
          Cinema after changes means you accept the updated terms.
        </p>
      </section>

      <p className={styles.footerNote}>
        Questions? See our <Link to="/privacy">Privacy Policy</Link> for how we handle your data.
      </p>
    </div>
  );
}